<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>graphs.Tests</AssemblyName>
    <RootNamespace>com.softwarearchetypes.graphs</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="csharp/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../graphs.csproj" />
  </ItemGroup>
</Project>